/**
 * The README's command table, rendered from `COMMANDS`.
 *
 * The table was hand-written and its own intro admitted it had drifted — five commands missing at
 * one point, `model probe` listed as a command name. `--help` is generated from the spec table and
 * cannot drift, so the README's copy is generated from the same one: `scripts/readme-commands.ts`
 * writes it between two markers, and `readme.test.ts` fails when the README disagrees with what
 * this renders. One source, two renderings, and a test rather than a sentence saying "keep in step".
 */

import { COMMANDS } from "#lib/commands"

export const TABLE_BEGIN =
    "<!-- commands:begin — generated by scripts/readme-commands.ts; do not edit by hand -->"
export const TABLE_END = "<!-- commands:end -->"

export function renderCommandTable(): string {
    const rows = COMMANDS.map((command) => `| \`${command.name}\` | ${command.summary} |`)
    return ["| Command | What it does |", "| --- | --- |", ...rows].join("\n")
}

/** The README with its table replaced, or `undefined` when the markers are missing. */
export function withCommandTable(readme: string): string | undefined {
    const begin = readme.indexOf(TABLE_BEGIN)
    const end = readme.indexOf(TABLE_END)
    if (begin === -1 || end === -1 || end < begin) return undefined
    return `${readme.slice(0, begin + TABLE_BEGIN.length)}\n${renderCommandTable()}\n${readme.slice(end)}`
}
