/**
 * The systemd user unit, as text.
 *
 * Pure in, pure out — which is the whole reason Linux could be supported at all. Nothing in this
 * project's test environment can run `systemctl --user` (a container has no systemd, a CI runner
 * has no user session bus), so the split is by what can be proven: the unit text is asserted here
 * line by line, and the lifecycle verbs refuse rather than pretend.
 */

import { describe, expect, test } from "bun:test"
import { BRAND } from "@dispach/core"
import type { ServicePlan } from "#lib/launchd"
import { ServiceSecretError } from "#lib/service-env"
import { assertUnitSafe, followUp, logCommand, quoteArg, renderUnit, unitPath } from "#lib/systemd"

const PLAN: ServicePlan = {
    label: "brand.server",
    programArguments: [
        "/usr/bin/node",
        "/opt/cli/index.js",
        "serve",
        "--store",
        "/home/x/store.db",
    ],
    workingDirectory: "/home/x/.brand",
    stdoutPath: "/home/x/.brand/logs/server/out.log",
    stderrPath: "/home/x/.brand/logs/server/err.log",
    environment: { HOME: "/home/x", PATH: "/usr/bin:/bin" },
    provenance: ["Generated by a test.", "Rewritten on every install."],
}

describe("the unit carries no secrets", () => {
    test("a key outside the allowlist throws, and the message names it", () => {
        try {
            renderUnit({ ...PLAN, environment: { MODEL_API_KEY: "sk-live" } }, BRAND.envPrefix)
            throw new Error("should have thrown")
        } catch (error) {
            expect(error).toBeInstanceOf(ServiceSecretError)
            const secret = error as ServiceSecretError
            expect(secret.code).toBe("daemon_secret_in_service")
            expect(secret.message).toContain("MODEL_API_KEY")
            // The same sentence launchd's renderer gives, because it is the same rule: the manager
            // echoes the environment in plaintext to anything running as this user.
            expect(secret.hint).toContain("plaintext")
        }
    })

    test("the allowlist is the same one the plist uses", () => {
        // One list, two renderers. A second copy is how one manager comes to permit a variable the
        // other refuses — and the dangerous direction is the one that silently permits more.
        const allowed = { HOME: "/h", PATH: "/p", TMPDIR: "/t" }
        expect(() => renderUnit({ ...PLAN, environment: allowed }, BRAND.envPrefix)).not.toThrow()
    })
})

describe("the rendered unit", () => {
    const body = renderUnit(PLAN, BRAND.envPrefix)

    test("restarts on failure only, with the same throttle as launchd", () => {
        // The 57 MB lesson, expressed in systemd's vocabulary: a configuration fault must stop the
        // service once rather than retry into a log nobody opens. `Restart=always` is the wrong
        // answer here for the same reason `KeepAlive: true` was.
        expect(body).toContain("Restart=on-failure")
        expect(body).not.toContain("Restart=always")
        expect(body).toContain("RestartSec=30")
        // Must exceed the runtime's own stop deadline, or the reaper that kills backgrounded `exec`
        // children never finishes and they outlive the service.
        expect(body).toContain("TimeoutStopSec=30")
    })

    test("it is a user unit wanted by the default target", () => {
        expect(body).toContain("WantedBy=default.target")
        // Not `multi-user.target`, which is a system unit's target and would need root.
        expect(body).not.toContain("multi-user.target")
    })

    test("the command and the working directory are absolute", () => {
        expect(body).toContain("ExecStart=/usr/bin/node /opt/cli/index.js serve")
        expect(body).toContain("WorkingDirectory=/home/x/.brand")
    })

    test("no log paths: the journal is the log", () => {
        // A journal rotates, is searchable, and survives a disk filling up — none of which an
        // append-only file does. `daemon logs` reads `journalctl` on this platform for that reason.
        expect(body).not.toContain("StandardOutput=")
        expect(body).not.toContain("StandardError=")
        expect(logCommand("brand.server")).toContain("journalctl --user")
    })

    test("the provenance is a comment, and systemd has somewhere to put it", () => {
        expect(body).toContain("# Generated by a test.")
        // Unlike launchd, where `Comment` does not exist and OpenClaw's is inert.
        expect(body.startsWith("#")).toBe(true)
    })
})

describe("values that would break a unit file", () => {
    test("a path with a space is quoted rather than split into two arguments", () => {
        // systemd splits `ExecStart` on whitespace, and `/Users/Some Name/` is an ordinary thing to
        // have — unquoted it becomes two arguments and the service runs the wrong command.
        expect(quoteArg("/Users/Some Name/bin/node")).toBe('"/Users/Some Name/bin/node"')
        expect(quoteArg("/usr/bin/node")).toBe("/usr/bin/node")
        expect(quoteArg('a"b')).toBe('"a\\"b"')
        expect(quoteArg("a\\b")).toBe('"a\\\\b"')
    })

    test("a newline is refused rather than silently truncating the line", () => {
        // A unit value runs to end of line, so this would produce a service that runs half a
        // command — which is worse than a command that fails here.
        expect(() => assertUnitSafe("/tmp/a\nb", "ExecStart")).toThrow(/newline/)
        expect(() => assertUnitSafe("/tmp/ab", "ExecStart")).not.toThrow()
        expect(() =>
            renderUnit({ ...PLAN, workingDirectory: "/tmp/a\nb" }, BRAND.envPrefix),
        ).toThrow(/newline/)
    })
})

describe("where the unit goes and what to run", () => {
    test("XDG_CONFIG_HOME wins when it is set", () => {
        expect(unitPath("brand.server", "/home/x", {})).toBe(
            "/home/x/.config/systemd/user/brand.server.service",
        )
        expect(unitPath("brand.server", "/home/x", { XDG_CONFIG_HOME: "/cfg" })).toBe(
            "/cfg/systemd/user/brand.server.service",
        )
        // An empty value is unset, not a root-relative path — the shape a sourced profile leaves.
        expect(unitPath("brand.server", "/home/x", { XDG_CONFIG_HOME: "" })).toContain(
            "/home/x/.config/",
        )
    })

    test("the follow-up names the linger command, which is not optional", () => {
        const lines = followUp("brand.server", "ada")
        expect(lines[0]).toContain("daemon-reload")
        expect(lines[1]).toContain("enable --now brand.server")
        // Without lingering a user unit stops when the last session ends, so an always-on server
        // installed over SSH is gone when the connection closes — launchd's `disable` trap in a
        // different costume.
        expect(lines[2]).toBe("loginctl enable-linger ada")
    })
})
