#!/usr/bin/env bun
/**
 * Generates the Homebrew formula for the published npm tarball.
 *
 * A generator rather than a committed file, because a formula is mostly a URL and a SHA-256 of a
 * release artefact — and a committed formula carrying a placeholder digest is the failure this repo
 * already has a rule about: a wrong number in a file outlives whoever guessed it, and the symptom
 * here is `brew install` refusing a download that is perfectly fine. So the digest is computed
 * from the tarball the release workflow just published, never typed.
 *
 * ## Node, not a compiled binary
 *
 * Until 0.1.3 the formula downloaded a `bun build --compile` binary per platform. Bun cannot complete
 * the WhatsApp handshake (see `packages/channel-whatsapp/src/transport.ts`), so the brew install
 * carried a channel it could not pair. The formula now `depends_on "node"` and installs the same
 * tarball `npm i -g dispach` installs — one runtime across every install path, and one artefact to
 * checksum instead of four.
 *
 * ## The service block
 *
 * `service do` is what makes `brew services start` work: a bare `serve` with no manifest, which hosts
 * the sandbox's enabled agents and reads that sandbox at every start. `run_type: :immediate` with
 * `keep_alive: { crashed: true }` mirrors the plist this project generates itself, deliberately: a
 * configuration fault must stop the service **once** rather than retry into a log nobody opens.
 *
 * **Homebrew never starts a service at install time**, whatever the formula says. So the caveat is
 * the only place a first-time user learns that one command away is an always-on API — and it names
 * both routes, because `brew services` and this project's own `daemon install` write *different*
 * units and running both would be two hosts contending for one lease.
 *
 * ## Usage
 *
 *     bun scripts/brew-formula.ts --version 0.1.3 --sha256 <digest>   > Formula/dispach.rb
 *     bun scripts/brew-formula.ts --version 0.1.3 --tarball ./dispach-0.1.3.tgz > Formula/dispach.rb
 *
 * The release workflow uses the first form, hashing the tarball it downloads from the registry after
 * `npm publish`; the second is for proving the formula locally against a `bun pm pack` output.
 */

import { createHash } from "node:crypto"
import { existsSync, readFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { DEFAULT_BRAND } from "../packages/core/src/brand.ts"

const ROOT = resolve(import.meta.dirname, "..")
const REPO = "moeen-mahmud/dispach"

function fail(message: string, hint: string): never {
    process.stderr.write(`\n  ${message}\n  hint: ${hint}\n\n`)
    process.exit(1)
}

function flag(name: string): string | undefined {
    const argv = process.argv.slice(2)
    const at = argv.indexOf(`--${name}`)
    if (at === -1) return undefined
    const value = argv[at + 1]
    if (value === undefined || value.startsWith("--")) {
        fail(`--${name} needs a value`, `For example: --${name} <value>`)
    }
    return value
}

function version(): string {
    const given = flag("version")
    if (given !== undefined) return given
    const pkg = JSON.parse(readFileSync(join(ROOT, "packages", "cli", "package.json"), "utf8")) as {
        readonly version: string
    }
    return pkg.version
}

/**
 * The digest, from `--sha256` or computed from `--tarball`. One of the two is required: a formula
 * with no digest is a formula Homebrew refuses, and guessing one is the failure this file exists to
 * prevent.
 */
function digest(): string {
    const given = flag("sha256")
    if (given !== undefined) {
        if (!/^[0-9a-f]{64}$/.test(given)) fail("--sha256 is not a SHA-256", `Read: ${given}`)
        return given
    }
    const tarball = flag("tarball")
    if (tarball === undefined) {
        fail(
            "No digest",
            "Pass --sha256 <digest> (the release workflow hashes the published tarball) or --tarball <path> to hash a local `bun pm pack` output.",
        )
    }
    if (!existsSync(tarball))
        fail(`No tarball at ${tarball}`, "Build one: cd packages/cli && bun pm pack")
    return createHash("sha256").update(readFileSync(tarball)).digest("hex")
}

const v = version()
const slug = DEFAULT_BRAND.slug
const sha = digest()
const pkg = "dispach"

process.stdout.write(`# Generated by scripts/brew-formula.ts — do not edit by hand.
#
# Regenerate with:
#   bun scripts/brew-formula.ts --version ${v} --sha256 <sha256 of the npm tarball> > Formula/${slug}.rb
class ${slug.charAt(0).toUpperCase()}${slug.slice(1)} < Formula
  desc "${DEFAULT_BRAND.name} — a model-agnostic AI agent runtime"
  homepage "https://github.com/${REPO}"
  url "https://registry.npmjs.org/${pkg}/-/${pkg}-${v}.tgz"
  sha256 "${sha}"
  license "Apache-2.0"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  service do
    # No manifest: the server hosts every agent in the sandbox that is not switched off, and it
    # re-reads the sandbox at every start — so an agent created tomorrow needs no change here.
    run [opt_bin/"${slug}", "serve"]
    # Not :always. A configuration fault has to stop this once rather than relaunch it thirty times
    # an hour into a log nobody opens. ${slug} status is where the reason shows up.
    keep_alive crashed: true
    run_type :immediate
    working_dir Dir.home
    log_path "#{Dir.home}/${DEFAULT_BRAND.stateDir}/logs/server/out.log"
    error_log_path "#{Dir.home}/${DEFAULT_BRAND.stateDir}/logs/server/err.log"
  end

  def caveats
    <<~EOS
      Start the always-on server, then create an agent:

        brew services start ${slug}
        ${slug} init

      Homebrew does not start a service at install time, so nothing is running yet. Anything
      that needs a host will offer to start one for you; ${slug} daemon uninstall undoes that.

      Use either brew services or ${slug} daemon install, not both. They write different
      service definitions, and two hosts would contend for the same agents.

      The agent's state lives in ~/${DEFAULT_BRAND.stateDir}. Secrets are read from a .env beside
      each agent's manifest and are never written into a service definition.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${slug} --version")
    (testpath/"agent.yaml").write <<~YAML
      apiVersion: ${DEFAULT_BRAND.apiVersion}
      id: brewtest
      name: Brew Test
      model:
        main:
          id: deepseek-v4-pro
          baseUrl: https://api.deepseek.com/v1
          apiKeyEnv: MODEL_API_KEY
    YAML
    ENV["MODEL_API_KEY"] = "not-used-by-validate"
    assert_match "brewtest", shell_output("#{bin}/${slug} validate #{testpath}/agent.yaml --json")
  end
end
`)
