#!/usr/bin/env bun
/**
 * Generates the Homebrew formula from binaries that actually exist.
 *
 * A generator rather than a committed file, because a formula is mostly four SHA-256 digests of
 * four release assets — and a committed formula carrying placeholder digests is the failure this
 * repo already has a rule about: a wrong number in a file outlives whoever guessed it, and the
 * symptom here is `brew install` refusing a download that is perfectly fine. So the digests come
 * from `dist-bin/*.sha256`, written by the release workflow beside the binaries it just built.
 *
 * ## What this deliberately does not include yet
 *
 * **No `service do` block.** That is what makes `brew services start` work, and it is the natural
 * home for the always-on server — but it would have to run `dispach serve` with no manifest, which
 * does not exist until Phase 16.2. A formula whose service block runs a command that refuses is
 * worse than one with no service block: `brew services start` reports success and the unit dies
 * into a log nobody has been told about. It arrives in 16.4 together with the thing it starts.
 *
 * **Homebrew never starts a service at install time**, whatever the formula says, so the caveat is
 * the only place a first-time user learns what to do next. It describes what works *today* and
 * gains the daemon sentence in 16.4.
 *
 * ## Usage
 *
 *     bun scripts/brew-formula.ts --version 0.1.0 > Formula/dispach.rb
 *     bun scripts/brew-formula.ts                  # version from packages/cli/package.json
 */

import { existsSync, readFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { DEFAULT_BRAND } from "../packages/core/src/brand.ts"

const ROOT = resolve(import.meta.dirname, "..")
const OUT_DIR = join(ROOT, "dist-bin")
const REPO = "moeen-mahmud/dispach"

/** Formula asset per platform, in the order Homebrew's `on_macos`/`on_linux` blocks want them. */
const ASSETS = [
    { id: "darwin-arm64", os: "macos", cpu: "arm" },
    { id: "darwin-x64", os: "macos", cpu: "intel" },
    { id: "linux-arm64", os: "linux", cpu: "arm" },
    { id: "linux-x64", os: "linux", cpu: "intel" },
] as const

function fail(message: string, hint: string): never {
    process.stderr.write(`\n  ${message}\n  hint: ${hint}\n\n`)
    process.exit(1)
}

function versionFromFlags(): string {
    const argv = process.argv.slice(2)
    const flag = argv.indexOf("--version")
    if (flag !== -1) {
        const value = argv[flag + 1]
        if (value === undefined || value.startsWith("--")) {
            fail("--version needs a value", "For example: --version 0.1.0")
        }
        return value
    }
    const pkg = JSON.parse(readFileSync(join(ROOT, "packages", "cli", "package.json"), "utf8")) as {
        readonly version: string
    }
    return pkg.version
}

/**
 * Read the digest `shasum -a 256` wrote, rather than hashing here.
 *
 * Reading the recorded digest means the formula asserts the same bytes the release publishes: if
 * the checksum file is missing, that asset was not built, and generating a formula that points at
 * it would produce a `brew install` failure at somebody else's terminal instead of here.
 */
function digest(id: string): string {
    const path = join(OUT_DIR, `${DEFAULT_BRAND.slug}-${id}.sha256`)
    if (!existsSync(path)) {
        fail(
            `No checksum for ${id}`,
            `Expected ${path}. Build every target first: \`bun run build:binary -- --all\`, then write checksums with \`shasum -a 256\`. The release workflow does both.`,
        )
    }
    const first = readFileSync(path, "utf8").trim().split(/\s+/)[0]
    if (first === undefined || !/^[0-9a-f]{64}$/.test(first)) {
        fail(`Checksum for ${id} is not a SHA-256`, `Read from ${path}: ${first ?? "(empty)"}`)
    }
    return first
}

const version = versionFromFlags()
const slug = DEFAULT_BRAND.slug
const url = (id: string) => `https://github.com/${REPO}/releases/download/v${version}/${slug}-${id}`

const blocks = ASSETS.map(
    (asset) => `  on_${asset.os} do
    on_${asset.cpu} do
      url "${url(asset.id)}"
      sha256 "${digest(asset.id)}"
      def install
        bin.install "${slug}-${asset.id}" => "${slug}"
      end
    end
  end`,
)

// One `on_macos`/`on_linux` pair per CPU rather than nested `on_arm`/`on_intel` inside one
// `on_macos`: Homebrew evaluates each block independently, so this reads as four flat cases and a
// fifth platform is one more block rather than a restructure.
process.stdout.write(`# Generated by scripts/brew-formula.ts — do not edit by hand.
#
# Regenerate with:
#   bun run build:binary -- --all
#   (cd dist-bin && for f in ${slug}-*; do shasum -a 256 "$f" > "$f.sha256"; done)
#   bun scripts/brew-formula.ts --version ${version} > Formula/${slug}.rb
class ${slug.charAt(0).toUpperCase()}${slug.slice(1)} < Formula
  desc "${DEFAULT_BRAND.name} — a model-agnostic AI agent runtime"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "Apache-2.0"

${blocks.join("\n\n")}

  def caveats
    <<~EOS
      Create an agent and talk to it:

        ${slug} init
        ${slug} run

      The agent's state lives in ~/${DEFAULT_BRAND.stateDir}. Secrets are read from a .env beside
      each agent's manifest and are never written into a service definition.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${slug} --version")
    (testpath/"agent.yaml").write <<~YAML
      apiVersion: ${DEFAULT_BRAND.apiVersion}
      id: brewtest
      name: Brew Test
      model:
        main:
          id: deepseek-v4-pro
          baseUrl: https://api.deepseek.com/v1
          apiKeyEnv: MODEL_API_KEY
    YAML
    ENV["MODEL_API_KEY"] = "not-used-by-validate"
    assert_match "brewtest", shell_output("#{bin}/${slug} validate #{testpath}/agent.yaml --json")
  end
end
`)
