#!/usr/bin/env bun
/**
 * Generates the Homebrew formula from binaries that actually exist.
 *
 * A generator rather than a committed file, because a formula is mostly four SHA-256 digests of
 * four release assets — and a committed formula carrying placeholder digests is the failure this
 * repo already has a rule about: a wrong number in a file outlives whoever guessed it, and the
 * symptom here is `brew install` refusing a download that is perfectly fine. So the digests come
 * from `dist-bin/*.sha256`, written by the release workflow beside the binaries it just built.
 *
 * ## The service block, and why it took until 16.4
 *
 * `service do` is what makes `brew services start` work, and it had to wait for the command it
 * runs: a bare `serve` with no manifest, which hosts the sandbox's enabled agents and reads that
 * sandbox at every start. Until 16.3 `serve` required a manifest, and a formula whose service block
 * ran a command that refuses is worse than one with no service block — `brew services start`
 * reports success and the unit dies into a log nobody has been told about.
 *
 * `run_type: :immediate` with `keep_alive: { crashed: true }` mirrors the plist this project
 * generates itself, deliberately: a configuration fault must stop the service **once** rather than
 * retry into a log nobody opens, which is the 57 MB lesson. `:always` would be the wrong answer
 * here for the same reason `KeepAlive: true` was.
 *
 * **Homebrew never starts a service at install time**, whatever the formula says. So the caveat is
 * the only place a first-time user learns that one command away is an always-on API — and it names
 * both routes, because `brew services` and this project's own `daemon install` write *different*
 * units and running both would be two hosts contending for one lease.
 *
 * ## Usage
 *
 *     bun scripts/brew-formula.ts --version 0.1.0 > Formula/dispach.rb
 *     bun scripts/brew-formula.ts                  # version from packages/cli/package.json
 */

import { existsSync, readFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { DEFAULT_BRAND } from "../packages/core/src/brand.ts"

const ROOT = resolve(import.meta.dirname, "..")
const OUT_DIR = join(ROOT, "dist-bin")
const REPO = "moeen-mahmud/dispach"

/** Formula asset per platform, in the order Homebrew's `on_macos`/`on_linux` blocks want them. */
const ASSETS = [
    { id: "darwin-arm64", os: "macos", cpu: "arm" },
    { id: "darwin-x64", os: "macos", cpu: "intel" },
    { id: "linux-arm64", os: "linux", cpu: "arm" },
    { id: "linux-x64", os: "linux", cpu: "intel" },
] as const

function fail(message: string, hint: string): never {
    process.stderr.write(`\n  ${message}\n  hint: ${hint}\n\n`)
    process.exit(1)
}

function versionFromFlags(): string {
    const argv = process.argv.slice(2)
    const flag = argv.indexOf("--version")
    if (flag !== -1) {
        const value = argv[flag + 1]
        if (value === undefined || value.startsWith("--")) {
            fail("--version needs a value", "For example: --version 0.1.0")
        }
        return value
    }
    const pkg = JSON.parse(readFileSync(join(ROOT, "packages", "cli", "package.json"), "utf8")) as {
        readonly version: string
    }
    return pkg.version
}

/**
 * Read the digest `shasum -a 256` wrote, rather than hashing here.
 *
 * Reading the recorded digest means the formula asserts the same bytes the release publishes: if
 * the checksum file is missing, that asset was not built, and generating a formula that points at
 * it would produce a `brew install` failure at somebody else's terminal instead of here.
 */
function digest(id: string): string {
    const path = join(OUT_DIR, `${DEFAULT_BRAND.slug}-${id}.sha256`)
    if (!existsSync(path)) {
        fail(
            `No checksum for ${id}`,
            `Expected ${path}. Build every target first: \`bun run build:binary -- --all\`, then write checksums with \`shasum -a 256\`. The release workflow does both.`,
        )
    }
    const first = readFileSync(path, "utf8").trim().split(/\s+/)[0]
    if (first === undefined || !/^[0-9a-f]{64}$/.test(first)) {
        fail(`Checksum for ${id} is not a SHA-256`, `Read from ${path}: ${first ?? "(empty)"}`)
    }
    return first
}

const version = versionFromFlags()
const slug = DEFAULT_BRAND.slug
const url = (id: string) => `https://github.com/${REPO}/releases/download/v${version}/${slug}-${id}`

const blocks = ASSETS.map(
    (asset) => `  on_${asset.os} do
    on_${asset.cpu} do
      url "${url(asset.id)}"
      sha256 "${digest(asset.id)}"
      def install
        bin.install "${slug}-${asset.id}" => "${slug}"
      end
    end
  end`,
)

// One `on_macos`/`on_linux` pair per CPU rather than nested `on_arm`/`on_intel` inside one
// `on_macos`: Homebrew evaluates each block independently, so this reads as four flat cases and a
// fifth platform is one more block rather than a restructure.
process.stdout.write(`# Generated by scripts/brew-formula.ts — do not edit by hand.
#
# Regenerate with:
#   bun run build:binary -- --all
#   (cd dist-bin && for f in ${slug}-*; do shasum -a 256 "$f" > "$f.sha256"; done)
#   bun scripts/brew-formula.ts --version ${version} > Formula/${slug}.rb
class ${slug.charAt(0).toUpperCase()}${slug.slice(1)} < Formula
  desc "${DEFAULT_BRAND.name} — a model-agnostic AI agent runtime"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "Apache-2.0"

${blocks.join("\n\n")}

  service do
    # No manifest: the server hosts every agent in the sandbox that is not switched off, and it
    # re-reads the sandbox at every start — so an agent created tomorrow needs no change here.
    run [opt_bin/"${slug}", "serve"]
    # Not :always. A configuration fault has to stop this once rather than relaunch it thirty times
    # an hour into a log nobody opens. ${slug} daemon status is where the reason shows up.
    keep_alive crashed: true
    run_type :immediate
    working_dir Dir.home
    log_path "#{Dir.home}/${DEFAULT_BRAND.stateDir}/logs/server/out.log"
    error_log_path "#{Dir.home}/${DEFAULT_BRAND.stateDir}/logs/server/err.log"
  end

  def caveats
    <<~EOS
      Start the always-on server, then create an agent:

        brew services start ${slug}
        ${slug} init

      Homebrew does not start a service at install time, so nothing is running yet. Anything
      that needs a host will offer to start one for you; ${slug} daemon uninstall undoes that.

      Use either brew services or ${slug} daemon install, not both. They write different
      service definitions, and two hosts would contend for the same agents.

      The agent's state lives in ~/${DEFAULT_BRAND.stateDir}. Secrets are read from a .env beside
      each agent's manifest and are never written into a service definition.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${slug} --version")
    (testpath/"agent.yaml").write <<~YAML
      apiVersion: ${DEFAULT_BRAND.apiVersion}
      id: brewtest
      name: Brew Test
      model:
        main:
          id: deepseek-v4-pro
          baseUrl: https://api.deepseek.com/v1
          apiKeyEnv: MODEL_API_KEY
    YAML
    ENV["MODEL_API_KEY"] = "not-used-by-validate"
    assert_match "brewtest", shell_output("#{bin}/${slug} validate #{testpath}/agent.yaml --json")
  end
end
`)
